### ISSUE TITLE
SMTPUTF8 mail command handling

### ISSUE THREAD

**Issue by cole** [agronholm/smtpproto#1]
It looks like smtpproto correctly handles the message body when the SMTPUTF8 extension is available. 

However, [per the spec](https://tools.ietf.org/html/rfc6531#section-3.4), the `MAIL FROM` command should include the `SMTPUTF8` option in that case. Currently there's no way to pass an option via the `mail` method. This could be solved by adding an options argument to that method.

It also seems like all output is always ASCII encoded. However, if SMTPUTF8 is supported and being used for the message, the `MAIL FROM` command (and subsequent `RCPT` commands) should be sent UTF-8 encoded.

**Comment by agronholm** [comment]
Thanks for the report. I'll incorporate this fix in the next release along with the PLAIN authentication fix.

**Comment by agronholm** [comment]
@cole you're welcome to review the PR.
