### ISSUE TITLE
SMTPUF8 extension should only be used when required 

### ISSUE THREAD

**Issue by cole** [agronholm/smtpproto#3]
From [RFC 6531](https://tools.ietf.org/html/rfc6531#section-3.4):

>    Because there is no guarantee that a next-hop SMTP server will
>    support the SMTPUTF8 extension, use of the SMTPUTF8 extension always
>    carries a risk of transmission failure.  In fact, during the early
>    stages of deployment for the SMTPUTF8 extension, the risk will be
>    quite high.  Hence, there is a distinct near-term advantage for
>    ASCII-only messages to be sent without using this extension.  The
>    long-term advantage of casting ASCII [ASCII] characters (0x7f and
>    below) as UTF-8 form is that it permits pure-Unicode environments.

So I think in practice, many (most?) servers will support SMTPUTF8, but we shouldn't use it unless the message requires it.

The stdlib smtplib module handles this by testing all of the address to see if any of them are non-ascii: https://github.com/python/cpython/blob/master/Lib/smtplib.py#L953. That's at the whole message level though.

The only way I can really see to resolve this is to add an option for smtputf8=True to the mail method and push handling of the problem upstream, because we need to send the SMTPUTF8 option with the MAIL comamnd if any of the recipient addresses is UTF-8, but when the mail method is called, we don't yet know the recipients.

_Originally posted by @cole in https://github.com/agronholm/smtpproto/pull/2#discussion_r550808122_

**Comment by agronholm** [comment]
I think there's something that I'm not understanding here. Why would a message containing only ASCII compatible addresses fail to be delivered when SMTPUTF8 is used?

**Comment by cole** [comment]
It won't fail on submission, but it may fail on the next hop. Using SMTPUTF8 requires that every SMTP server in the delivery chain supports SMTPUTF8. That's something that is still not guaranteed, so using SMTPUTF8 carries a risk that the message won't be delivered.

I don't have any information on how widely SMTPUTF8 is supported currently. I believe it's common, but not 100%.

**Comment by agronholm** [comment]
Why would it fail on the next hop if there are only ASCII compatible addresses on the recipient list?

**Comment by cole** [comment]
Because it's been specified in the MAIL FROM command. If we specify SMTPUTF8 as an option there, that means the message requires SMTPUTF8. The server accepts that at face value (and least, that's the RFC behaviour); it doesn't look at the message and see that it's just ASCII.

I think RFC 6531 is clear on this:

> If the SMTPUTF8-aware SMTP client is aware that neither the envelope nor the message being sent requires any of the SMTPUTF8 extension capabilities, it SHOULD NOT supply the SMTPUTF8 parameter with the MAIL command.

**Comment by agronholm** [comment]
I think you may be misunderstanding the RFC. It's the use of *unicode email addresses* that carries the risk of failing on the next hop, not SMTPUTF8 itself which only enables the SMTP server to accept such addresses. I didn't see anything in the RFC that says the server must use this extension on the delivery to the next hop even if it doesn't deem it necessary.

**Comment by agronholm** [comment]
What smtpproto does now is also RFC compliant: since it won't know beforehand if the addresses need SMTPUTF8, it always uses it when available.

**Comment by cole** [comment]
Most servers will look for the presence of unicode email addresses, e.g. [postfix does](http://www.postfix.org/SMTPUTF8_README.html#using). I don't know we can say that all do though. You're correct that the RFC doesn't say anything about the `SMTPUTF8` being the sole determinant. That's the case I'm concerned about though.

I still don't think smtpproto is complaint, though, because it will violate the part of the RFC I've already quoted (clearly we're reading this differently):

> If the SMTPUTF8-aware SMTP client is aware that neither the envelope nor the message being sent requires any of the SMTPUTF8 extension capabilities, it SHOULD NOT supply the SMTPUTF8 parameter with the MAIL command.

To me, smtpproto is (or is intended to be used to build) SMTPUTF8-aware SMTP clients, so if we know what the message is and that it doesn't require UTF8, we should not supply the parameter.

You can argue that smtpproto is not aware what the message requires, at least not at the point we need to send the SMTPUTF8 param. Any higher level library that uses smtpproto should be aware though.

Maybe a clearer way to state this, is I would like to build logic like this: https://github.com/python/cpython/commit/8308444eefee8a6b5bb58b9f51a29d1a8d3683bf into aiosmtplib while using stmpproto, and I don't think I can do that currently.

**Comment by agronholm** [comment]
So what you would like to have is a way to opt out of SMTPUTF8 support during `MAIL FROM` and `RCPT TO`?

**Comment by agronholm** [comment]
Closed via #4.
